---
:nick: elfari-test
:server: irc.freenode.net
:channels:
  - "#elfari-test"
:abiquo:
  :host: mothership
  :user: admin
  :password: xabiquo

:gitdude:
  :repos:
    - :name: Abiquo
      :path: '/Users/rubiojr/git/abiquo'
    - :name: Abiquo Enterprise
      :path: '/Users/rubiojr/git/abiquo-enterprise'
        
